### ISSUE TITLE
密码登录异常

### ISSUE THREAD

**Issue by Seayay** [Kaidesuyo/Hydrogen-Music#11]
复现步骤：
1. 使用邮箱登录（*手机号登录未知* ）
2. 登陆失败（*可能不需要此步骤* ）
3. 头像 --> 退出登录
4. 我的音乐 --> 登录网易云账号 --> 邮箱登录
截图：
![image](https://user-images.githubusercontent.com/92374733/218244878-3d4dfa55-cc35-457e-9e37-5f23252228e7.png)

**Comment by Kaidesuyo** [comment]
网易最近也为邮箱登录增加了二次验证，暂时绕不过，请使用二维码登录
