### ISSUE TITLE
在windows11深色模式下字体颜色显示异常

### ISSUE THREAD

**Issue by Ghz114514** [Kaidesuyo/Hydrogen-Music#18]
![image](https://user-images.githubusercontent.com/111216078/218287920-005d02ea-bf19-4c24-a550-36fcf76232c7.png)
如图所示

**Comment by Ghz114514** [comment]
![image](https://user-images.githubusercontent.com/111216078/218288933-3ea99769-511f-4bfa-a4eb-65ab9e6f28a2.png)

**Comment by Kaidesuyo** [comment]
已修复，会在下个版本更新
