### ISSUE TITLE
歌词显示问题

### ISSUE THREAD

**Issue by Ghz114514** [Kaidesuyo/Hydrogen-Music#22]
![image](https://user-images.githubusercontent.com/111216078/218289079-5bd0931e-e500-40b6-8e72-2934c85a34ed.png)

**Comment by Ghz114514** [comment]
![image](https://user-images.githubusercontent.com/111216078/218289093-5a224bce-9f6f-486d-895a-d56a5a43323c.png)

**Comment by ArthurZhou** [comment]
在设置里把字号调小可以解决

**Comment by Kaidesuyo** [comment]
已修复，在下个版本中更新
![image](https://user-images.githubusercontent.com/36076659/218292158-c94196b0-9ec7-4937-b44c-1b49f2c841c6.png)
