### ISSUE TITLE
关闭播放界面后播放栏出现白条

### ISSUE THREAD

**Issue by Ghz114514** [Kaidesuyo/Hydrogen-Music#25]
https://user-images.githubusercontent.com/111216078/218293457-7c7e34c7-e6ea-4129-9b50-aa421db5f741.mp4

返回方式是点击hydrogen

**Comment by Ghz114514** [comment]
鼠标悬浮到播放条后正常

**Comment by Kaidesuyo** [comment]
在该问题出现后，如果随意调整窗口大小后白条消失的话，说明在代码层面没有问题，推测可能涉及到windows底层显示原理且与分辨率有关。

**Comment by Ghz114514** [comment]
已经可以确定是Windows的问题了，感谢回复
