### ISSUE TITLE
【Bug】取消歌词显示后出现黑条

### ISSUE THREAD

**Issue by 30000lightyears** [Kaidesuyo/Hydrogen-Music#27]
![image](https://user-images.githubusercontent.com/66123770/218306507-db3c8c5b-cc8b-4c28-9fa8-14e9994b232d.png)
![image](https://user-images.githubusercontent.com/66123770/218306520-cdd2bd8e-04b9-4e89-846a-97c723c5c60c.png)
甚至可以像显示歌词的时候一样点击切换进度……

**Comment by Kaidesuyo** [comment]
原本是作为自由组合歌词功能使用，现在已将其改为歌词显示与隐藏功能，将在下个版本更新
