### ISSUE TITLE
[BUG] 对于正在播放歌词过长的处理

### ISSUE THREAD

**Issue by Sun-Glove** [Kaidesuyo/Hydrogen-Music#33]
![image](https://user-images.githubusercontent.com/63444399/218307518-54ffc62f-82be-4214-a737-e436ca442043.png)
![image](https://user-images.githubusercontent.com/63444399/218307565-99781371-34d5-48fb-bf1b-f81dd3b61794.png)
图为正常歌词和过长歌词的比对，应有所调整

**Comment by Sun-Glove** [comment]
若超出长度甚至会丢失部分歌词

**Comment by Kaidesuyo** [comment]
重复的issue #22 ,请在发布issue前检查该issue是否已被提及
