### ISSUE TITLE
歌曲名‘g‘字母显示遮挡问题

### ISSUE THREAD

**Issue by Ghz114514** [Kaidesuyo/Hydrogen-Music#40]
![image](https://user-images.githubusercontent.com/111216078/218463203-abb654b9-605d-4d19-adeb-14727d413e54.png)
不确定是否有其他字母也会出现半遮挡问题

**Comment by Ghz114514** [comment]
更改缩放依旧

**Comment by Kaidesuyo** [comment]
已修复
