### ISSUE TITLE
添加视频功能-登录后反而没有显示清晰度选项

### ISSUE THREAD

**Issue by CastleYu** [Kaidesuyo/Hydrogen-Music#42]
![图片](https://user-images.githubusercontent.com/61407907/218533514-a60eba75-970d-4a36-82d5-1f2bd6da5a37.png)

**Comment by CastleYu** [comment]
* 安装方式： exe安装版
* 系统：Windows10
未登录时 正常
先搜索出后登录，缓存时始终显示0%

**Comment by Kaidesuyo** [comment]
已修复
