### ISSUE TITLE
【Bug】底部任务栏悬停预览出现错误

### ISSUE THREAD

**Issue by 30000lightyears** [Kaidesuyo/Hydrogen-Music#46]
正在播放的歌曲：
![image](https://user-images.githubusercontent.com/66123770/218914368-2e2b841f-bd14-4410-9566-9141d889a08a.png)
显示的歌曲：
![image](https://user-images.githubusercontent.com/66123770/218914441-51b90314-4c6a-4b3e-b6f3-8989de8882e8.png)

**Comment by 30000lightyears** [comment]
> 发现问题了，是这里会显示下一首播放歌曲而非正在播放的歌曲

更正，是“播放列表”下一首歌曲

**Comment by Kaidesuyo** [comment]
已修复
