### ISSUE TITLE
窗口模式下歌词界面的当前歌词过长的话会被吞掉一部分

### ISSUE THREAD

**Issue by piper030** [Kaidesuyo/Hydrogen-Music#47]
貌似只有英文歌会有这种问题
![image](https://user-images.githubusercontent.com/125424271/218916474-49735344-e8db-472c-a518-8f5782efa3dd.png)

**Comment by 30000lightyears** [comment]
#22  #33 似乎提及了这个问题，作者说在0.3.1修复了这个问题。

**Comment by piper030** [comment]
是我没认真看，抱歉

**Comment by ArthurZhou** [comment]
如果问题解决，请关闭此issue
