### ISSUE TITLE
创建任务名称问题

### ISSUE THREAD

**Issue by Ghz114514** [Kaidesuyo/Hydrogen-Music#49]
![image](https://user-images.githubusercontent.com/111216078/218959923-28f6f5b5-da74-4a0c-ba15-d0d0ae8b335a.png)
只能说太离谱了，估计涉及内核了

**Comment by Kaidesuyo** [comment]
这个不用创建issue，Electron应用就是这样，具体请参见Electron实现原理。

**Comment by Ghz114514** [comment]
有可能，毕竟Windows11dev bug一大堆
