### ISSUE TITLE
[bug]版本号错误

### ISSUE THREAD

**Issue by HuaJi2333DaDa** [Kaidesuyo/Hydrogen-Music#58]
![image](https://user-images.githubusercontent.com/30079825/219932047-6afc7e8f-7b32-4757-b369-b2c7ec995c23.png)
![image](https://user-images.githubusercontent.com/30079825/219932063-9e348da6-43a2-4a28-a618-e4e3af7b2bc0.png)
如图，下载安装的是0.3.1，显示的版本号是0.3.0

**Comment by 30000lightyears** [comment]
0.4.0版本已经修复
