### ISSUE TITLE
建议：增加Cookie登录通道

### ISSUE THREAD

**Issue by zby1211** [Kaidesuyo/Hydrogen-Music#67]
我翻了一下NeteaseCloudMusicApi，应该是支持直接提交cookie的？
因为一些很麻烦的原因我异地只能邮箱/Cookie二选一，而且这情况还挺常见的，现在没得登入有点尴尬。
当然如果这功能没人用的话我就自己去构建好了。。。

**Comment by Kaidesuyo** [comment]
目前，你可以打开应用按下Ctrl+Shift+F12快捷键打开控制台，在localStorage中添加Token（cookie中的MUSIC_U字段）来间接实现。
具体操作及字段名如以下视频所示：
https://user-images.githubusercontent.com/36076659/221341163-a9fa0182-42a9-49d9-a5ce-dec0c67fdf1b.mp4

**Comment by zby1211** [comment]
多谢！！！！
