### ISSUE TITLE
添加视频建议

### ISSUE THREAD

**Issue by sws2pm** [Kaidesuyo/Hydrogen-Music#8]
是否可以添加本地视频作为播放背景，手动替换缓存视频后时间轴依旧是下载视频，无法完整是对上本地视频

**Comment by Kaidesuyo** [comment]
其实那个删除按钮原本就是添加本地视频按钮（但是我当时赶时间就偷懒了XD

- 该功能将在重构后实现

折中方案：

1. 进入该地址：
![image](https://user-images.githubusercontent.com/36076659/218244122-75b03745-8dbf-460e-bb99-56fa33374b12.png)
C:\Users\Kai（PC用户名）\AppData\Roaming（隐藏文件夹）\hydrogenmusic

2. 找到musicVideo.json文件并打开。
3. 参照原本的格式修改图中的path字段即可（最新追加的视频位于末尾）。
![image](https://user-images.githubusercontent.com/36076659/218244184-6a8dd384-51e9-4f1b-8010-fae98e72c049.png)

您可能会遇到的问题：

- 不支持的视频格式
- 视频文件质量过高而导致的应用卡顿
- 添加的本地视频如果存在音轨，会与歌曲一起播放
