### ISSUE TITLE
重构进度？

### ISSUE THREAD

**Issue by 13584452567** [Kaidesuyo/Hydrogen-Music#96]
想问问佬，重构进度如何了？
顺便，新年快乐！

**Comment by Kaidesuyo** [comment]
新年快乐！
感谢您的关心，进度我不太好说，能说的是重构之后会变成一个偏底层的本地播放器，功能上是希望也能稍微满足一些hifi发烧友的需求，同时也在添加插件系统，这样像一些在线音源也能通过外挂插件的方式引入，包括一些其他的功能也能通过第三方插件实现。

**Comment by 13584452567** [comment]
> 新年快乐！
> 感谢您的关心，进度我不太好说，能说的是重构之后会变成一个偏底层的本地播放器，功能上是希望也能稍微满足一些hifi发烧友的需求，同时也在添加插件系统，这样像一些在线音源也能通过外挂插件的方式引入，包括一些其他的功能也能通过第三方插件实现。
> 

这个插件的开发也是使用js嘛？

**Comment by Kaidesuyo** [comment]
是的，这样第三方开发者也能快速上手

**Comment by 13584452567** [comment]
> 是的，这样第三方开发者也能快速上手

十分感谢佬的回答。期待您重构完成的Hydrogen Music
