### ISSUE TITLE
"Seeking Assistance with Interface Navigation in Hydrogen Music Application"

### ISSUE THREAD

**Issue by HollieRose89** [Kaidesuyo/Hydrogen-Music#97]
Hello Hydrogen Music development team,

I hope this message finds you well.

After downloading and using your Hydrogen Music application, I encountered a few issues. I was wondering how I could switch to the layout shown in your repository's README file (![image](https://github.com/Kaidesuyo/Hydrogen-Music/assets/161124344/42d21505-a236-4817-bd7e-1c94b28ae6de)) when playing the song "Keep the Torch." This is the interface I see upon launching the application (
![image](https://github.com/Kaidesuyo/Hydrogen-Music/assets/161124344/6b66d49c-fadf-4f75-a2d8-b7a85f433343)
)
![image](https://github.com/Kaidesuyo/Hydrogen-Music/assets/161124344/092a0fec-177b-4fbd-bd14-3b8dd92c7c60)
. It would be greatly appreciated if you could provide any help on how to configure it to navigate to that page.

Warm regards,
Hollie Rose

////////////////////////////////////////

您好 Hydrogen Music 的开发团队，

(我的中文不是很好哈~）
希望你们一切都好。

在下载并使用你们的 Hydrogen Music 软件应用后，我遇到了一些问题。我想知道如何在播放“Keep the Torch”这首歌曲时切换到你们仓库 README 文件中显示的布局（please see the attached files above）。这是我在启动应用程序时看到的界面（please see the attached files above）。
如果你们能提供任何帮助，告诉我如何配置它以导航到那个页面，我将不胜感激。

祝好，
Hollie Rose

**Comment by ArthurZhou** [comment]
https://github.com/Kaidesuyo/Hydrogen-Music/assets/89689293/87208526-a86a-4430-9a01-c1912861bffa


btw, you need a bilibili account to add videos with 720p and 1080p resolution
